---
collections:

  - name: ansible.builtin
    version: 1.0.

  - name: ansible.posix
    version: 1.4.0

  - name: community.general
    version: 2.0.

  - name: https://github.com/redhat-cop/network.backup
    type: git

  - name: my_organization.my_collection
    version: 1.2.3
    source: https://github.com/my_organization/my_collection.git
